# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Novoda Open Source
email: info@novoda.com
description: Novodaâ€™s Open Source projects help you write cleaner, more responsive, automated code, and provide some of the greatest tools for agile software development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://novoda.github.io" # the base hostname & protocol for your site
twitter_username: novoda
github_username:  novoda

# Build settings
markdown: kramdown
